### ISSUE TITLE
Update UI to reflect new design

### ISSUE THREAD

**Issue by ianconsolata** [filecoin-project/on-chain-voting#74]
The UXIT team at the Filecoin Foundation did a full review of the user flows for the app, and we'd like to update the UI to reflect their recommendations. Each issue in this design will be broken into separate tickets and linked in the tasklist below.

[StorSwift Power Vote.pdf](https://github.com/user-attachments/files/15537139/StorSwift.Power.Vote.pdf)

```[tasklist]
### Tasks
- [x] Add landing page including FAQ
- [x] Ensure keyboard accessibility
- [x] Create color coordinated status badges for proposals, including separate badges for accepted and rejected.
- [x] Change UCAN Delegates button to Connect GitHub
- [x] Align branding with Filecoin branding (blue buttons, Filecoin logo, etc)
- [x] Update links and logos in footer
- [x] Display Github usernames and icons instead of wallet addressess when possible
- [x] Reformat vote list to match designs
- [x] Update "Message" info to "Details"
- [x] update proposal creation flow
```
